const desserts = [
    {
        dessertId: 0,
        dessertName: `HERSHEY'S “Perfectly Chocolate” Chocolate Cake`,
        author: 'Dana Bandana',
        description: 'Bake this delicious dessert when you’re hosting the next family get-together, celebrating a birthday or wanting a bite of delicious chocolate cake after dinner.',
        totalTimeInMinutes: 45,
        img: '../../../assets/images/desserts/chocolatcake.png',
        difficultyLevel: 'Easy',
        ingredients: [
            {name: 'Sugar', quantity: 2, unit: 'cup'},
            {name: 'Flour', quantity: 0.75, unit: 'cup'},
            {name: `HERSHEY'S Cocoa`, quantity: 1, unit: 'teaspoon'},
            {name: 'Baking powder', quantity: 1, unit: 'teaspoon'},
            {name: 'Baking soda', quantity: 1, unit: 'teaspoon'},
            {name: 'vanilla extract', quantity: 2, unit: 'teaspoon'},
            {name: 'Milk', quantity: 1, unit: 'cup'},
            {name: 'Eggs', quantity: 2, unit: 'object'},
        ],
        howToPrepare: '1.Heat oven to 350°F. Grease and flour two 9-inch round baking pans. 2.Stir together sugar, flour, cocoa, baking powder, baking soda and salt in large bowl. Add eggs, milk, oil and vanilla; beat on medium speed of mixer 2 minutes. Stir in boiling water (batter will be thin). Pour batter into prepared pans. 3. Bake 30 to 35 minutes or until wooden pick inserted in center comes out clean. Cool 10 minutes; remove from pans to wire racks. Cool completely. Frost with "Perfectly Chocolate" Chocolate Frosting.',
        dessertType: ['Cake', 'Chocolate']
    },
    {
        dessertId: 1,
        dessertName: 'Macarons',
        author: 'Shahar Shpitaler',
        description: 'sometimes you need to change it up with something a little fancier: enter macarons. ' +
            'They may seem intimidating but with our easy-to-follow guide, they don’t have to be',
        totalTimeInMinutes: 80,
        img: '../../../assets/images/desserts/macarons.jpg',
        difficultyLevel: 'Easy',
        Ingredients: [
            {name: 'powdered sugar', quantity: 1, unit: 'cup'},
            {name: 'almond flour', quantity: 1, unit: 'cup'},
            {name: `salt`, quantity: 1, unit: 'cup'},
            {name: 'Egg whites', quantity: 3, unit: 'object'},
            {name: 'granulated sugar', quantity: 0.5, unit: 'cup'},
            {name: 'vanilla extract', quantity: 0.5, unit: 'teaspoon'},
            {name: 'Milk', quantity: 1, unit: 'cup'},
            {name: 'Vanilla extract', quantity: 2, unit: 'teaspoon'},
            {name: 'pink gel food coloring', quantity: 2, unit: 'drops'},
        ],
        How_to_prepare: '1.Make the macarons: In the bowl of a food processor, combine the powdered sugar, almond flour, and ½ teaspoon of salt, and process on low speed, until extra fine.Sift the almond flour mixture through a fine-mesh sieve into a large bowl In a separate large bowl, beat the egg whites and the remaining ½ teaspoon of salt with an electric hand mixer until soft peaks form. Gradually add the granulated sugar until fully incorporated. Continue to beat until stiff peaks form (you should be able to turn the bowl upside down without anything falling out).3. Add the vanilla and beat until incorporated. Add the food coloring and beat until just combined.',
        dessertType: ['cookie', 'vanilla']
    },
    {
        dessertId: 2,
        dessertName: 'New york cheese cake',
        author: 'Racheli Eliyahu',
        description: 'With this recipe, a creamy, gorgeous, crack-free New York-style cheesecake is totally doable, even for beginners!',
        totalTimeInMinutes: '70',
        img: '../../../assets/images/desserts/cheesecake-8.jpg',
        difficultyLevel: 'Easy',
        Ingredients: [
            {name: 'Philadelphia cheese', quantity: 900, unit: 'gram'},
            {name: 'golden caster sugar', quantity: 250, unit: 'gram'},
            {name: 'plain flour', quantity: 3, unit: 'teaspoon'},
            {name: 'zest of lemon', quantity: 2, unit: 'teaspoon'},
            {name: 'lemon juice', quantity: 1.5, unit: 'teaspoon'},
            {name: 'vanilla extract', quantity: 1.5, unit: 'teaspoon'},
            {name: 'eggs', quantity: 3, unit: 'object'},
            {name: 'carton soured cream', quantity: 248, unit: 'ml'},
        ],
        How_to_prepare: '1.Position an oven shelf in the middle of the oven. Heat the oven to 180C/ 160C fan/ gas 4. 2. Line the base of a 23cm springform cake tin by putting a square piece of parchment paper or foil on top of the tin base and then clipping the side on so the paper or foil is trapped and any excess sticks out of the bottom.3.For the crust, melt 85g butter in a medium pan. Stir in 140g digestive biscuit crumbs and 1 tbsp golden caster or granulated sugar so the mixture is evenly moistened.4.Press the mixture into the bottom of the pan and bake for 10 minutes. Cool on a wire rack while preparing the filling.5.For the filling, increase the oven temperature to fan 220C/ 200C fan/ gas 7. In a table top mixer fitted with the paddle attachment, beat 900g full-fat soft cheese at medium-low speed until creamy, about 2 minutes.6.With the mixer on low, gradually add 250g golden caster sugar, then 3 tbsp plain flour and a pinch of salt, scraping down the sides of the bowl and the paddle twice.',
    },
];

